### ISSUE TITLE
원문에 Em Dash(—)가 있고, 번역문에 ASCII Hyphen(-)을 넣었을 경우 경고

### ISSUE THREAD

**Issue by darkcircle** [changwoo/ko-po-check#33]
드물게 나오는 케이스지만 그놈 인터페이스 지침에 따라 ASCII 코드 영역의 특수문자 대신 유니코드 영역의 문자를 채용하는 케이스가 점점 늘어나고 있는데,
일반적으로 번역할 때 Em Dash와 ASCII Hyphen을 동일하게 볼 수 있어 이 부분에 대한 감지 및 수정 유도가 필요해보입니다.

참고상 기록용으로 남겨둡니다.

**Comment by changwoo** [comment]
https://github.com/changwoo/ko-po-check/pull/36  머지. 감사합니다.
