### ISSUE TITLE
파일 인코딩과 Content-Type 인코딩 일치

### ISSUE THREAD

**Issue by darkcircle** [changwoo/ko-po-check#37]
#35 번 PR과 관련해서 ....
파일들을 확인해보니 인코딩에 대한 접근을 두가지 관점에서 봐야겠네요.

- 파일 자체 인코딩 (이를테면 .... `file view.py` 셸 실행 결과 `view.py: Python script text executable, ASCII text`)
- 파일 내부 '헤더 엔트리'에서 언급하는 'MIME Type and Charset' (`"Content-Type: text/plain; charset=UTF-8\n"`)

말씀대로 (가급적이면 현재로서는 UTF-8 이면 좋겠지만) 파일 인코딩이 꼭 UTF-8 일 거라는 보장도 없고 ASCII나 ISO-8859 계열 인코딩이 UTF-8의 일부가 될 수 있다는걸 감안하면 #35 번 커밋 자체가 문제 접근 방식 이전에 문제 인지 단계부터 잘못됐다는 결론이 나옵니다(...).

------

그렇다면, 파일 인코딩과 내용 인코딩의 문제 여부를 확인하기 위해서라면, ko-po-check 이전에 뭔가 enc-po-check 같은게 돌아야 할 것 같은데, 파일/내용 인코딩 검사한다고 바닥부터 완전히 새로 만드는건 오바고 파일 자체 인코딩을 확인하는 루틴 부분만 새로 짜고, ko-po-check 내부 코드 일부를 활용해서 헤더 엔트리를 검사하게 하면 얼추 문제가 해결되지 않을까 싶긴 합니다.

다만, ko-po-check 코드를 보면 expat 라이브러리를 제외하고 별 다른 의존성이 걸려있지 않은데, expat이야 docbook이라는 중요한 데이터 타겟이 있으니까 쓸 수 밖에 없지만 어쩌다가 해도 되고 안해도 될 것 같은 (메인 기능도 아닌) 파일 자체 인코딩 검사를 위해 (굳이?) 외부 라이브러리를 하나 더 끌어오는게 과연 바람직한 구현 방향이냐......

여기까진 문제를 코드로 해결하는 그냥 방법론적인(trivial) 이야기고, 굳이 이 이슈를 코드로 따로 구현을 할 필요가 있느냐,... po 전용 편집기를 쓰면 알아서 해주는데 말이죠. 가끔 UTF-8 인코딩 지원 편집기 안쓰고 MS 메모장 같은 곳에서 디폴트 인코딩 CP949로 저장해버리는 경우가 만에 하나 아주 가끔 있는 일이라 이런 일 때문에 시간과 노력을 희생(???)할 필요가 있는지...

이 이슈에서 확실히 정해서 기록으로 남겨둘 필요가 있을 것 같습니다. 요새 편집기 프로그램이 워낙 좋아졌기 때문에 굳이 이런 수고를 할 필요가 없다고 보는 주의지만, 정말 필요하다면 그때 가서 구현하겠죠.

**Comment by darkcircle** [comment]
참고로 ... 
Content-Type(과 실제 문자열) 인코딩은 파일 인코딩 값과 같거나 하위 집합 요소 중 하나여야 합니다.
그렇지 않으면 파일을 열었을 때 깨져서 나오거나 제대로 내용이 나타나지 않을 수 있습니다.

**Comment by changwoo** [comment]
종료. 잘못 만들어진 파일 고려하는 상상할 필요 없어요.
